In [3]:
import numpy as np

In [ ]:
a = np.array([1 , 2 , 3 , 4 , 5 , 6])
print(a[1:4])
print(a[::2])
print(a[::-1])


[2 3 4]
[1 3 5]
[6 5 4 3 2 1]


In [19]:
a = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
#printing first coloumn
print(a[:,0])
#printing first row
print(a[0,:])
#printing a block of elements
print(a[0:2 , 1:3])
#printing a specific element in a 2d array
print(a[0:1 , 0 :1])

[1 4 7]
[1 2 3]
[[2 3]
 [5 6]]
[[1]]


In [23]:
#copy vs view in slice
#View--->Original Array Gets Changed
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])
view = arr[1:4]
view[0] = 999
print(arr)
#Here In This Example Original Array Is Changed

[  1 999   3   4   5   6]


In [27]:
#copy
arr = np.array([1 , 2 , 3 , 4])
copy= arr[1:3].copy()
copy[0] = 200
print(copy)
print(arr)

[200   3]
[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])

In [35]:
print(arr[2,::])
print(arr[:,3])
print(arr[0:2])

[ 9 10 11 12]
[ 4  8 12 16]
[[1 2 3 4]
 [5 6 7 8]]


In [38]:
print(arr[::2 , ::2])

[[ 1  3]
 [ 9 11]]


In [42]:
arr_3d = np.array([[[1 , 2 , 3] , [4 , 5 , 6]] , [[7 , 8 , 9 ] , [10 , 11 , 12]]])
print(arr_3d.shape)

(2, 2, 3)


In [51]:
#Slicing 3d arrays
#single layer
print(arr[0])
print(arr_3d[0:2 , 0:2 ,0:2])

[1 2 3 4]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [62]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]],

    [[13, 14, 15],
     [16, 17, 18]]
])
print(arr[1:3, 0 , :])

[[ 7  8  9]
 [13 14 15]]


In [6]:
#3D Array problems
a = np.arange(24).reshape(2, 3, 4)
print(a)
print(a.shape , a.size , a.ndim , a.dtype)
print(a[0] , a[1] , a[0,2] , a[1,1,3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4) 24 3 int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] [ 8  9 10 11] 19


In [ ]:
print(a)
print(a[0:2 , : , 0])
print(a[0:2 , 2 , :])
print(a[0 , : , 1:3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  4  8]
 [12 16 20]]
[[ 8  9 10 11]
 [20 21 22 23]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [16]:
a.sum(axis = 0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
marks = np.random.randint(40, 100, (5, 4, 3))
np.mean(marks , axis = 1)





array([[77.  , 67.5 , 64.  ],
       [64.5 , 71.5 , 48.25],
       [73.75, 79.  , 76.75],
       [60.  , 71.  , 77.25],
       [55.5 , 81.25, 67.5 ]])

SyntaxError: positional argument follows keyword argument (1065652354.py, line 1)