In [2]:
import numpy as np

In [4]:
arr = np.array([1 , 2 , 4])
print(arr)

[1 2 4]


In [5]:
#Python Lists Vs Numpy Arrays
import time

In [13]:
py_list = list(range(1000000))
start = time.time()
multiplied = [x*2 for x in py_list]
t = time.time() - start
print(t)

arr = np.arange(1000000)
begin = time.time()
marr = arr *2
end = time.time() - begin
print(end)#20-50x faster

0.01987910270690918
0.00034928321838378906


In [14]:
#creating arrays from lists
a = np.array([1 , 2 , 3])#1d arrays from a list manual creation
b = np.array([1 , 4 , 5 ,6 , 6])
print(a)
print(b)

[1 2 3]
[1 4 5 6 6]


In [23]:
#creating arrays from builtin method
a = np.zeros((2 , 3))
b = np.ones((2 , 3))
c = np.eye(3)
d = np.full((2 , 2) , 7)
e = np.arange(1 , 1000 , 2)
f = np.random.rand(2 , 2)
g = np.linspace(0 ,1 , 5)
print(a , b , c , d , e ,f ,g)


[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[7 7]
 [7 7]] [  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 4

In [ ]:
#Properties Of Arrays
a = np.array([1 , 2 , 3] , dtype='float64')#We Can Force
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

(3,)
3
1
float64


In [37]:
#Reshaping Arrays
a=np.arange(2 , 12)
a.reshape(2,5)
a.reshape(-1 , 2)
x = a.flatten()#copy Is Created No Change to original array
print(x)
x[0] = 999
print(a)
y = a.ravel()#replaces original
y[0] = 999
print(y)
print(a)

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10 11]
[999   3   4   5   6   7   8   9  10  11]
[999   3   4   5   6   7   8   9  10  11]


In [45]:
a= np.array([[1, 2 , 3] , [4 , 5 , 6]])
#normal indexing
print(a[0])
print(a[1 , 2])
#Boolean Indexing
print(a[a>3])#Under A Rule
#Fancy Indexing
b = np.array([1 , 2 , 4])
print(b[[0 , 1 , 2]])

[1 2 3]
6
[4 5 6]
[1 2 4]
